POST http://localhost:5000/promotions/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjcxNGE1MTcyYTI3NTFmZGYyZDIyMGMiLCJpYXQiOjE3MTg3MDA2NDF9.CG7gKpj8_pJc61W9hGqBcvf9HrdJYsTiaf__hFEP2x8
Content-Type: application/json

{
    "title": "Super Sale!",
    "description": "Don't miss out on our super sale!",
    "newPrice": 50,
    "oldPrice": 100,
    "label": "Sale",
    "image": "super_sale.jpg",
    "isFeatured": true,
    "defaultImage": "default_promo_image.jpg",
    "available": true,
    "archive": false
}