POST http://localhost:5000/order/
Content-Type: application/json

{
    "order_date": "2024-04-04T15:00:00.000Z",
    "delivery_type": "Доставка",
    "foods": ["<product_id_1>", "<product_id_2>"],
    "name": "John Doe",
    "email": "johndoe@example.com",
    "phone": "1234567890",
    "date": "2024-04-04",
    "time": "12:00 PM",
    "message": "No special requests",
    "consent": true
}
