DELETE http://localhost:5000/product/661390663d3c29904aaa7ce9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjcxNGE1MTcyYTI3NTFmZGYyZDIyMGMiLCJpYXQiOjE3MTg3MDA2NDF9.CG7gKpj8_pJc61W9hGqBcvf9HrdJYsTiaf__hFEP2x8


