 GET http://localhost:5000/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU0NDlhYWNlZTdlNmQ4MWIzZWRhZDIiLCJpYXQiOjE3MDk0NjEzNTN9.EasmeEmdg60B3-A3eOO2h5HLRH4K9QWHcJaTs0f_jqo