PUT http://localhost:5000/promotions/6641ca01414c996d970fd276
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjcxNGE1MTcyYTI3NTFmZGYyZDIyMGMiLCJpYXQiOjE3MTg3MDA2NDF9.CG7gKpj8_pJc61W9hGqBcvf9HrdJYsTiaf__hFEP2x8
Content-Type: application/json

{
    "title": "Updated Sale",
    "description": "Updated description for the sale",
    "newPrice": 4444444444444440,
    "oldPrice": 899990,
    "label": "Updated Sale",
    "image": "updated_sale.jpg",
    "isFeatured": true,
    "defaultImage": "default_promo_image.jpg",
    "available": true,
    "archive": false
}