PUT http://localhost:5000/product/6645b18165fcda1f94f1cf19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjcxNGE1MTcyYTI3NTFmZGYyZDIyMGMiLCJpYXQiOjE3MTg3MDA2NDF9.CG7gKpj8_pJc61W9hGqBcvf9HrdJYsTiaf__hFEP2x8
Content-Type: application/json

{
    "topCategory": "exampleTopCategory",
    "subCategory": "exampleSubCategory",
    "category": "aarregrghf",
    "weight": "exampleWeight",
    "name": "dfffffffffffffff",
    "price": 22,
    "description": "bla fsbla",
    "action": false,
    "new": false,
    "discount": true,
    "archive": false,
    "displayInDeliveryMenu": false,
    "hideInMenu": false,
    "quantity": 1
}

# PUT http://localhost:5000/product/id HTTP/1.1

