PUT http://localhost:5000/reservations/661384ce8ee6282baed8f094
Content-Type: application/json

{
    "customerName": "zfzxvzxvczxczxczxczx",
    "phoneNumber": "0987654321",
    "email": "janesmith@example.com",
    "date": "2024-04-05",
    "time": "1:00 PM",
    "numberOfPeople": 6555555555555555555555555,
    "tableNumber": 5,
    "specialRequests": "Vegetarian meal request",
    "status": "confirmed",
    "consentToProcessPersonalData": true
}
