PUT http://localhost:5000/feedback/6645b583639a31a4844aa4a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjcxNGE1MTcyYTI3NTFmZGYyZDIyMGMiLCJpYXQiOjE3MTg3MDA2NDF9.CG7gKpj8_pJc61W9hGqBcvf9HrdJYsTiaf__hFEP2x8
Content-Type: application/json

{
    "name": "Jane Smith",
    "email": "janesmith@example.com",
    "phone": "0987654321",
    "message": "This is an updated feedback message",
    "consent": true,
    "status": "progress", 
    "archive": true 
}

