PUT http://localhost:5000/order/660b06cd0da9126eec84e19e
Content-Type: application/json

{
    "order_date": "2023-07-09",
    "delivery_type": "Доставка",
    "foods": [
        "64a6e97dab987804bd4cd38a",
        "64a9686b3c3ca99001da9d26"
    ],
    "name": "Jane Smidddddddth",
    "email": "janesmith@example.com",
    "phone": "+123456789",
    "date": "2023-07-09",
    "time": "1:00 PM",
    "message": "Vegetarian meal request",
    "consent": true
}
