PUT http://localhost:5000/product/661390663d3c29904aaa7ce9 HTTP/1.1
Content-Type: application/json

{
            "category":"aarregrghf",
            "name":"dfffffffffffffff",
            "discount_price": 37777,
            "price":22,
            "unit":"kg",
            "available":false,
            "description":"bla fsbla",
            "favourite":true
           
}

# PUT http://localhost:5000/product/id HTTP/1.1

