PUT http://localhost:5000/feedback/6645b583639a31a4844aa4a8
Content-Type: application/json

{
    "name": "Jane Smith",
    "email": "janesmith@example.com",
    "phone": "0987654321",
    "message": "This is an updated feedback message",
    "consent": true,
    "status": "progress", 
    "archive": true 
}

